name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm ci
      - run: npm run build

      - name: rsync deployments
        uses: contention/rsync-deployments@v2.0.0
        with:
          # Initial/required rsync flags
          flags:
            -a --delete --filter 'protect *.htaccess' --filter 'protect sitemap.xml' --filter 'protect robots.txt'
            # Exclude flags and directory pairs
          excludes:
            ""
            # The server user
          user:
            admin
            # The deployment target
          host:
            marcel-gregor.de
            # The local path to sync
          localpath:
            /dist/portfolio/
            # The remote path to sync
          remotepath:
            /var/www/ftpserver
            # The private key
          deploy_key: ${{ secrets.DEPLOY_KEY_ }}
